# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-06-19 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='item_count',
            field=models.IntegerField(default=0),
        ),
    ]
